version: 0.2

phases:
    build:
        commands:
            - echo 'Building Services App............'
            - mvn  clean package
        
artifacts:
    files: '**/*'
    base-directory: target/BlogWebsite
    
cache:
  paths:
    - '/root/.m2/**/*'